name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        run: |
          # Команда для деплоя на сервер
          ssh 176.123.165.113 "cd help_bot_port && git pull origin main"
