name: Update Server on Push

on:
  push:
    branches:
      - master # Укажи свою ветку, на которой ты хочешь отслеживать изменения

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: SSH to server and update repository
        run: |
          ssh 176.123.165.113 "cd help_bot_port && git pull"

