name: Update Server on Push

on:
  push:
    branches:
      - master # Укажи свою ветку, на которой ты хочешь отслеживать изменения

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to server and update repository
        run: |
          ssh 176.123.165.113 "cd /path/to/repository && git pull"

