name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create SSH directory
      run: mkdir -p $HOME/.ssh

    - name: Copy SSH private key
      run: echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set correct permissions for SSH key
      run: chmod 600 $HOME/.ssh/id_rsa

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - run: set -eu

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Deploy to server
      run: ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no staks@176.123.165.113 "echo 'Deployment successful'"
