name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - run: set -eu
    - run: mkdir "$HOME"
    - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/id_rsa_dop"
    - run: chmod 600 "$HOME/id_rsa_dop"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Deploy to server
      run: rsync -e "ssh -i $HOME/key -o StrictHostKeyChecking=no" --archive --compress --delete . staks@176.123.165.113:/help_bot_port
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
