name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create SSH directory
      run: mkdir -p $HOME/.ssh

    - name: Copy SSH private key
      run: echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set correct permissions for SSH key
      run: chmod 400 $HOME/.ssh/id_rsa

    - name: Add SSH key to the SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - run: python -m pip install --upgrade pip
    - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Deploy to server
      run: ssh staks@176.123.165.113 "echo 'Deployment successful'"
